# Generated by Django 5.2.8 on 2025-12-03 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='StrategyExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('conservative', 'Conservative Strategy'), ('balanced', 'Balanced Strategy'), ('growth', 'Growth Strategy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('apy_range', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=20)),
                ('how_it_works', models.TextField()),
                ('ideal_users', models.TextField()),
                ('pros', models.TextField(help_text='JSON array of advantages')),
                ('cons', models.TextField(help_text='JSON array of disadvantages')),
                ('recommended_minimum', models.CharField(blank=True, help_text="e.g., '10 cUSD'", max_length=50)),
                ('recommended_duration', models.CharField(blank=True, help_text="e.g., '3-6 months'", max_length=100)),
                ('historical_performance', models.JSONField(blank=True, default=dict, help_text='Historical APY data')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Strategy explanations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Session ID for anonymous users', max_length=100)),
                ('message', models.TextField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context like user_data, timestamps, etc.')),
                ('model_used', models.CharField(default='gemini-2.0-flash-exp', max_length=50)),
                ('response_source', models.CharField(choices=[('api', 'API Response'), ('fallback', 'Fallback Response'), ('cached', 'Cached Response')], default='api', max_length=20)),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens used in this exchange')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Auto-generated title for the conversation', max_length=200)),
                ('user_context', models.JSONField(blank=True, default=dict, help_text='User data/context for this session')),
                ('total_tokens', models.IntegerField(default=0)),
                ('message_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')])),
                ('feedback_text', models.TextField(blank=True)),
                ('response_helpful', models.BooleanField(blank=True, help_text='Was the response helpful?', null=True)),
                ('suggested_improvement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_assistant.conversation')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_assistant.conversationsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeFiTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=100, unique=True)),
                ('short_definition', models.CharField(max_length=200)),
                ('detailed_explanation', models.TextField()),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('strategy', 'Strategy'), ('security', 'Security'), ('platform', 'Platform Specific')], default='basic', max_length=50)),
                ('search_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for search')),
                ('usage_examples', models.TextField(blank=True, help_text='JSON array of usage examples')),
                ('popularity_score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_terms', models.ManyToManyField(blank=True, to='ai_assistant.defiterm')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(default='gemini-2.0-flash-exp', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'created_at'], name='ai_assistan_user_id_4153fd_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session_id', 'created_at'], name='ai_assistan_session_b1c493_idx'),
        ),
    ]
