/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MoolaAddresses,
  MoolaAddressesInterface,
} from "../../../contracts/IMoola.sol/MoolaAddresses";

const _abi = [
  {
    inputs: [],
    name: "CELO_ALFAJORES",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CEUR_ALFAJORES",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CUSD_ALFAJORES",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LENDING_POOL_ALFAJORES",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MCELO_ALFAJORES",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MCEUR_ALFAJORES",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MCUSD_ALFAJORES",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610298610052600b82828239805160001a6073146045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100875760003560e01c80635a7f0616116100655780635a7f0616146100e6578063d319d90d14610104578063d52d935414610122578063fe96cc961461014057610087565b80632c2a15861461008c57806330d093c1146100aa57806336df4519146100c8575b600080fd5b61009461015e565b6040516100a19190610247565b60405180910390f35b6100b2610176565b6040516100bf9190610247565b60405180910390f35b6100d061018e565b6040516100dd9190610247565b60405180910390f35b6100ee6101a6565b6040516100fb9190610247565b60405180910390f35b61010c6101be565b6040516101199190610247565b60405180910390f35b61012a6101d6565b6040516101379190610247565b60405180910390f35b6101486101ee565b6040516101559190610247565b60405180910390f35b730886f74eeec443fbb6907fb5528b57c28e81312981565b73874069fa1eb16d44d622f2e0ca25eea172369bc181565b73f194afdf50b03e69bd7d057c1aa9e10c9954e4c981565b7310c892a6ec43a53e45d0b916b4b7d383b1b78c0f81565b7371db38719f9113a36e14f409bad4f07b58b4730b81565b7386f61eb83e10e914fc6f321f5dd3c2dd4860a00381565b7332974c7335e649932b5766c5ae15595afc26916081565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061023182610206565b9050919050565b61024181610226565b82525050565b600060208201905061025c6000830184610238565b9291505056fea2646970667358221220148514eb8908fdda9d3a8ec0e3c0e5c899ba6b4f45fa7b88b4d01abba5bae8c864736f6c634300081c0033";

type MoolaAddressesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MoolaAddressesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MoolaAddresses__factory extends ContractFactory {
  constructor(...args: MoolaAddressesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MoolaAddresses & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MoolaAddresses__factory {
    return super.connect(runner) as MoolaAddresses__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MoolaAddressesInterface {
    return new Interface(_abi) as MoolaAddressesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MoolaAddresses {
    return new Contract(address, _abi, runner) as unknown as MoolaAddresses;
  }
}
