/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iMoolaSol from "./IMoola.sol";
export type { iMoolaSol };
export type { AttestifyVault } from "./AttestifyVault";
export type { ISelfProtocol } from "./ISelfProtocol";
export type { MockMoolaLendingPool } from "./MockMoolaLendingPool";
export type { MockSelfProtocol } from "./MockSelfProtocol";
export type { MockToken } from "./MockToken";
