/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAaveSol from "./IAave.sol";
export type { iAaveSol };
import type * as mockAaveSol from "./MockAave.sol";
export type { mockAaveSol };
export type { AttestifyVault } from "./AttestifyVault";
export type { ISelfProtocol } from "./ISelfProtocol";
export type { MockSelfProtocol } from "./MockSelfProtocol";
export type { MockToken } from "./MockToken";
