/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAadhaarRegisterCircuitVerifier } from "./IAadhaarRegisterCircuitVerifier";
export type { IRegisterCircuitVerifier } from "./IRegisterCircuitVerifier";
