/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMToken } from "./IMToken";
export type { IMoolaLendingPool } from "./IMoolaLendingPool";
export type { MoolaAddresses } from "./MoolaAddresses";
