/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MoolaAddressesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CELO_ALFAJORES"
      | "CEUR_ALFAJORES"
      | "CUSD_ALFAJORES"
      | "LENDING_POOL_ALFAJORES"
      | "MCELO_ALFAJORES"
      | "MCEUR_ALFAJORES"
      | "MCUSD_ALFAJORES"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CELO_ALFAJORES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CEUR_ALFAJORES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CUSD_ALFAJORES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LENDING_POOL_ALFAJORES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MCELO_ALFAJORES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MCEUR_ALFAJORES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MCUSD_ALFAJORES",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CELO_ALFAJORES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CEUR_ALFAJORES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CUSD_ALFAJORES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LENDING_POOL_ALFAJORES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MCELO_ALFAJORES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MCEUR_ALFAJORES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MCUSD_ALFAJORES",
    data: BytesLike
  ): Result;
}

export interface MoolaAddresses extends BaseContract {
  connect(runner?: ContractRunner | null): MoolaAddresses;
  waitForDeployment(): Promise<this>;

  interface: MoolaAddressesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CELO_ALFAJORES: TypedContractMethod<[], [string], "view">;

  CEUR_ALFAJORES: TypedContractMethod<[], [string], "view">;

  CUSD_ALFAJORES: TypedContractMethod<[], [string], "view">;

  LENDING_POOL_ALFAJORES: TypedContractMethod<[], [string], "view">;

  MCELO_ALFAJORES: TypedContractMethod<[], [string], "view">;

  MCEUR_ALFAJORES: TypedContractMethod<[], [string], "view">;

  MCUSD_ALFAJORES: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CELO_ALFAJORES"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CEUR_ALFAJORES"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CUSD_ALFAJORES"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LENDING_POOL_ALFAJORES"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MCELO_ALFAJORES"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MCEUR_ALFAJORES"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MCUSD_ALFAJORES"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
